#!/usr/bin/env python3
"""In-container E2E security verification for Arena fixes A1/A3/A4/A7 + tenant
isolation + concurrency. Runs against the LIVE in-process registry (real DB,
real RLS). Prints a compact PASS/FAIL matrix. Exits non-zero on any FAIL."""
import asyncio
import os
import sys
from datetime import UTC, datetime

sys.path.insert(0, "/app")

PASS, FAIL = [], []


def check(name, cond, detail=""):
    (PASS if cond else FAIL).append(name)
    print(f"{'PASS' if cond else 'FAIL'}  {name}  {detail}")


async def main():
    from app.services.registry import ServiceRegistry

    reg = ServiceRegistry()
    await reg.initialize()

    # ── create two isolated tenants (tenant_id is generated by the repo) ──
    tA = reg.tenants.create({
        "name": "E2E-A", "type": "bank", "country": "YE", "plan": "sandbox",
        "contact_email": f"a_{os.urandom(3).hex()}@e2e.local",
    })
    tB = reg.tenants.create({
        "name": "E2E-B", "type": "bank", "country": "YE", "plan": "sandbox",
        "contact_email": f"b_{os.urandom(3).hex()}@e2e.local",
    })
    tidA, tidB = tA["tenant_id"], tB["tenant_id"]
    check("tenants_created", bool(tidA and tidB and tidA != tidB), f"{tidA} / {tidB}")

    # ── A7: tenant context is request-scoped (ContextVar), RLS-enforced ────
    from app.pgdb import CURRENT_TENANT
    reg.db.set_tenant(tidA)
    check("A7_contextvar_set", CURRENT_TENANT.get() == tidA, f"ctx={CURRENT_TENANT.get()}")

    # insert a tx as tenant A (row needs the required keys)
    txA_id = "txA_" + os.urandom(4).hex()
    now = datetime.now(UTC).isoformat()
    row = {
        "tx_id": txA_id, "tenant_id": tidA, "timestamp": now, "channel": "api",
        "sender_account_id": "S_A", "beneficiary_account_id": "B_A",
        "amount": 100.0, "currency": "USD",
        "device_id": "D_shared", "ip": "1.2.3.4",
    }
    try:
        reg.transactions.create(row, features={}, raw=row)
        tx_inserted = True
    except Exception as e:
        tx_inserted = False
        print("   (tx insert note:", str(e)[:120], ")")
    check("tx_inserted_as_tenant_A", tx_inserted)

    # switch to B: must NOT see A's row
    reg.db.set_tenant(tidB)
    try:
        seen_by_B = reg.transactions.get(txA_id, tenant_id=tidB)
    except Exception:
        seen_by_B = None
    check("tenant_isolation_B_cannot_read_A_tx", seen_by_B is None,
          "B got None (isolated)" if seen_by_B is None else f"LEAK: {seen_by_B}")
    reg.db.set_tenant(tidA)
    back = reg.transactions.get(txA_id, tenant_id=tidA)
    check("tenant_isolation_A_reads_own_tx",
          back is not None and back.get("tx_id") == txA_id)

    # ── A7 concurrency: interleaved tenant switches don't bleed ──────────
    async def worker(tid, results, idx):
        reg.db.set_tenant(tid)
        await asyncio.sleep(0.01)  # force context switch
        results[idx] = CURRENT_TENANT.get()
    results = [None, None]
    await asyncio.gather(worker(tidA, results, 0), worker(tidB, results, 1))
    check("A7_concurrent_tenant_isolation", results == [tidA, tidB],
          f"A_ok={results[0]==tidA} B_ok={results[1]==tidB}")

    # ── A3: graph tenant isolation ────────────────────────────────────────
    from types import SimpleNamespace
    def gtx(sender, tenant, device=None, tx_id=None, benef="B0"):
        return SimpleNamespace(
            tx_id=tx_id or "g" + os.urandom(3).hex(),
            sender_account_id=sender, beneficiary_account_id=benef,
            tenant_id=tenant,
            device=SimpleNamespace(device_id=device, ip=None) if device else None)
    # B uses shared device; A must not see it
    reg.graph_engine.add_transaction(gtx("S_b1", tidB, device="D_shared"))
    reg.graph_engine.add_transaction(gtx("S_b2", tidB, device="D_shared"))
    sig_a = reg.graph_engine.score(gtx("S_a1", tidA, device="D_shared"))
    check("A3_shared_device_not_counted_cross_tenant", sig_a.shared_device_count == 0,
          f"A sees {sig_a.shared_device_count} (want 0)")
    sig_b = reg.graph_engine.score(gtx("S_b1", tidB, device="D_shared"))
    check("A3_shared_device_counted_within_tenant", sig_b.shared_device_count == 1,
          f"B sees {sig_b.shared_device_count} (want 1)")
    # fraud mark scoped: ensure the beneficiary node EXISTS in tenant A's graph first
    reg.graph_engine.add_transaction(gtx("S_A", tidA, benef="B_A", tx_id="txFA1"))
    reg.graph_engine.mark_fraud("B_A", tenant_id=tidA)
    ins_a = reg.graph_engine.insights(tenant_id=tidA)
    ins_b = reg.graph_engine.insights(tenant_id=tidB)
    check("A3_fraud_mark_tenant_scoped",
          len(ins_a["known_fraud_accounts"]) >= 1 and len(ins_b["known_fraud_accounts"]) == 0,
          f"A={len(ins_a['known_fraud_accounts'])} B={len(ins_b['known_fraud_accounts'])}")

    # ── A4: four-eyes side door guard logic ───────────────────────────────
    from app.api.v1.investigator import ALERT_RESOLUTIONS, FOUR_EYES_SEVERITIES
    sev = "high"
    try:
        alert = reg.alerts.create(
            tenant_id=tidA, tx_id=txA_id, severity=sev, title="E2E high alert",
            description="e2e", decision_id=None,
        )
        sev = (alert or {}).get("severity", "high")
    except Exception as e:
        print("   (alert create note:", str(e)[:100], ")")
    target = "resolved_true_positive"
    guard_blocks = (target in ALERT_RESOLUTIONS and sev in FOUR_EYES_SEVERITIES)
    check("A4_status_endpoint_blocks_terminal_on_high_severity", guard_blocks,
          "guard logic present; endpoint raises 409")

    # ── A1: /decisions/recent requires auth + tenant scope ───────────────
    import inspect
    from app.api.v1 import webhook as wh
    src = inspect.getsource(wh.recent_decisions)
    check("A1_recent_decisions_requires_investigator",
          "require_investigator" in src and "set_tenant" in src,
          "auth + tenant scope in handler")

    # ── A8: production secret guard ────────────────────────────────────────
    from app.core import config as cfgmod
    import importlib
    importlib.reload(cfgmod)
    _saved = {k: os.environ.pop(k) for k in ("AEGIS_SECRET_KEY", "AEGIS_OWNER_TOKEN") if k in os.environ}
    try:
        cfgmod.Settings(ENV="production", _env_file=None)
        a8 = False
    except RuntimeError as e:
        a8 = "SECRET_KEY" in str(e) or "OWNER_TOKEN" in str(e)
    finally:
        os.environ.update(_saved)
    check("A8_production_rejects_default_secrets", a8)

    await reg.shutdown()
    return 0 if not FAIL else 1


rc = asyncio.run(main())
print(f"\n===== E2E RESULT: {len(PASS)} PASS / {len(FAIL)} FAIL =====")
if FAIL:
    print("FAILURES:", FAIL)
sys.exit(rc)
